services:
    - docker

before_install:
    - docker --version

install:
    - image="dves"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm -it "$image" ffmpeg -version
    - docker run --rm -it "$image" ffmsindex
